//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace oop_laba_2
{
	class Cashier:Worker
	{
		public Cashier (Person obj)
		{
			this.name = obj.Name;
			this.surname = obj.Surname;
			this.Id = obj.Id;
		}
		public override void Work()
		{
			Console.WriteLine ("Oh, it is a cashier");
		}
	}
}

