//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace oop_laba_2
{
	class Person
	{
		protected string name, surname;
		public virtual int Id{ get; set;}
		public string Name{
			get{return name;}
		}
		public string Surname{
			get{return surname;}
		}
		public Person(string name, string surname)
		{
			this.name = name;
			this.surname = surname;
		}
		public Person(){}
		public virtual void Work()
		{
			Console.WriteLine ("Unemployed person");
		}
	}
}

