//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace oop_laba_2
{
	class Worker:Person
	{
		int id;
		public override int Id{
			get {return id;}
			set{id = value;}
		}
		public Worker(string name, string surname, int id){
			this.name = name;
			this.surname = surname;
			this.id = id;
		}
		public  Worker(){
		}
		public Worker(string name, string surname):base(name, surname)
		{
			
		}
		public override void Work()
		{
			Console.WriteLine ("Just a worker");
		}
	}
}

